#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b gcc5-20190314 gcc

export ARCH=arm64
export KBUILD_BUILD_USER=FauzanD
export KBUILD_BUILD_HOST=SemaphoreCI
export USE_CCACHE=1
export CACHE_DIR=~/.ccache

make -C $(pwd) O=out riva-perf_defconfig
make -C $(pwd) CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-gnu- O=out -j6 -l4

cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
cd AnyKernel
zip -r9 WinX-Pie-GCC5-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
