#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b linaro8-20190216 gcc
git clone https://github.com/najahiiii/clang.git -b llvm9 llvm9
GCC="$(pwd)/gcc/bin/aarch64-linux-gnu-"
CT="$(pwd)/llvm9/bin/clang"
CLANG_TRIPLE=aarch64-linux-gnu-
CLANG_LD=aarch64-linux-gnu-ld.gold
curl -s -F chat_id=722516461 -F sticker="CAADBAADNwIAAqN9MRU0Uzcb30UCIwI" https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendSticker
curl -s -X POST https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendMessage?chat_id=722516461 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>WinX Kernel CAF</b> new build"'!'"%0AStarted on <code>$(hostname)</code>%0AFor device <b>RIVA</b> (Redmi 5A)%0Abranch <code>$(git rev-parse --abbrev-ref HEAD)</code>%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${GCC}gcc --version | head -n 1)</code>%0AClang <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested%0A<b>Semaphore CI Build Info</b> - <a href='https://semaphoreci.com/fauzandhiyaul/android_kernel_xiaomi_msm8917'>Status</a>"
tanggal=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=FauzanDF
export CLANG_TRIPLE
export CLANG_LD
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
# Function to upload to ix.io
function sprunge() {
    cat build.log | curl -F 'sprunge=<-' http://sprunge.us > link
    HASIL="$(cat link)"
}
# Function to upload to del.dog
function deldog() {
    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
        echo "ERROR: failed to post document" >&2
        exit 1
    }
    KEY=$(jq -r .key <<< "${RESULT}")
    echo "https://del.dog/raw/${KEY}"
}
# Fin Error
function finerr() {
        sprunge
        curl -s -X POST https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendMessage?chat_id=722516461 -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s) | <b>Build logs</b> <a href='${HASIL}'>here</a>"
        exit 1
}
make -s -C $(pwd) O=out riva-perf_defconfig
make -s -C $(pwd) CC=${CT} CROSS_COMPILE=${GCC} O=out -j6 -l8 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
sprunge
cd AnyKernel
zip -r9 WinXKernel-Pie-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="722516461" -F document=@"WinXKernel-Pie-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | <b>Logs</b> <a href='${HASIL}'>here</a> | #riva" https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendDocument
cd ..
rm -rf out
rm -rf AnyKernel/zImage
rm -rf AnyKernel/WinXKernel*.zip
