#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
GCC="~/gcc/bin/aarch64-linux-gnu-"
curl -s -F chat_id=-1001163257618 -F sticker="CAADBQADNwADoOTBMXWCfMxbi4L3FgQ" https://api.telegram.org/bot832348112:AAHwaetZW8HnIDP_bgbhOMw6BLVu6W75N1I/sendSticker
curl -s -X POST https://api.telegram.org/bot832348112:AAHwaetZW8HnIDP_bgbhOMw6BLVu6W75N1I/sendMessage?chat_id=-1001163257618 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>ScrapperKernel</b>%0ACompile Started"'!'"%0AFor device <b>RIVA</b> (Redmi 5A)%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler</b> <code>$(${GCC}gcc --version | head -n 1)| sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested"
tanggal=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=zantrash
export KBUILD_BUILD_HOST=scrp
# Fin Error
function finerr() {
        curl -s -X POST https://api.telegram.org/bot832348112:AAHwaetZW8HnIDP_bgbhOMw6BLVu6W75N1I/sendMessage?chat_id=-1001163257618 -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s)"
        exit 1
}
make -s -C $(pwd) O=out riva_defconfig
make -s -C $(pwd) CROSS_COMPILE=${GCC} O=out -j10
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
cd AnyKernel
zip -r9 scrapper-kernel-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001163257618" -F document=@"scrapper-kernel-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | #riva" https://api.telegram.org/bot832348112:AAHwaetZW8HnIDP_bgbhOMw6BLVu6W75N1I/sendDocument
cd ..
rm -rf out
rm -rf AnyKernel/zImage
rm -rf AnyKernel/scrapper*.zip
